import { expect } from '@playwright/test';
import { randomBytes } from 'node:crypto';
import { join } from 'node:path';

export async function runAccessE2E({ page, base, temp }) {
  const password = randomBytes(20).toString('hex');
  const accessData = await (await page.request.get(`${base}/api/settings/access`)).json();
  const maintenance = accessData.expenseCategories.find(category => category.name === 'Maintenance');
  const penalties = accessData.expenseCategories.find(category => category.name === 'Penalties');
  expect(maintenance).toBeTruthy();
  expect(penalties).toBeTruthy();
  await page.goto(`${base}/settings`);
  await expect(page.getByRole('heading', { name: 'Settings', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Roles & permissions', exact: true }).click();
  await page.getByRole('button', { name: 'Create role', exact: true }).click();
  await page.getByLabel('Role name', { exact: true }).fill('Loads viewer');
  await page.getByLabel('View imported loads').check();
  await page.getByLabel('Maintenance View', { exact: true }).check();
  await page.getByLabel('Maintenance Add', { exact: true }).check();
  await page.getByRole('button', { name: 'Save role', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: 'Loads viewer', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Users', exact: true }).click();
  await page.getByRole('button', { name: 'Add user', exact: true }).click();
  await page.getByLabel('Name', { exact: true }).fill('Access viewer');
  await page.getByLabel('Email', { exact: true }).fill('access-viewer@example.com');
  await page.getByLabel('Password', { exact: true }).fill(password);
  await page.getByLabel('Role', { exact: true }).selectOption({ label: 'Loads viewer' });
  await page.getByLabel('Active account').uncheck();
  await page.getByRole('button', { name: 'Create user', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const row = page.getByRole('row').filter({ hasText: 'access-viewer@example.com' });
  await expect(row).toContainText('Disabled');
  await row.getByRole('button', { name: 'Edit', exact: true }).click();
  await page.getByLabel('Active account').check();
  await page.getByRole('button', { name: 'Save changes', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(row).toContainText('Active');
  const context = await page.context().browser().newContext();
  const viewer = await context.newPage();
  const errors = [];
  viewer.on('pageerror', error => errors.push(error.message));
  try {
    await viewer.goto(`${base}/login`);
    await viewer.getByLabel('Email or existing username', { exact: true }).fill('access-viewer@example.com');
    await viewer.getByLabel('Password', { exact: true }).fill(password);
    await viewer.getByLabel('Trust this device for 30 days', { exact: false }).check();
    await viewer.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(viewer).toHaveURL(`${base}/loads`);
    await expect(viewer.locator('aside').getByRole('link', { name: 'Expenses & Charges', exact: true })).toBeVisible();
    await expect(viewer.locator('aside').getByRole('link', { name: 'Expenses & Charges settings', exact: true })).toHaveCount(0);
    expect((await viewer.request.get(`${base}/api/expenses?categoryId=${maintenance.id}&page=1&pageSize=10`)).status()).toBe(200);
    expect((await viewer.request.get(`${base}/api/expenses?categoryId=${penalties.id}&page=1&pageSize=10`)).status()).toBe(403);
    const viewerSession = await (await viewer.request.get(`${base}/api/auth/session`)).json();
    expect(viewerSession.user.expenseCategoryAccess).toEqual(expect.arrayContaining([
      expect.objectContaining({ categoryId: maintenance.id, canView: true, canCreate: true, canEdit: false, canDelete: false }),
    ]));
    const cookie = (await context.cookies()).find(c => c.name === 'mserp_session');
    expect(cookie.expires - Date.now()/1000).toBeGreaterThan(29 * 86400);
    await expect(viewer.locator('aside').getByRole('link', { name: 'Settings', exact: true })).toBeVisible();
    expect((await viewer.request.get(`${base}/api/settings/access`)).status()).toBe(403);
    await viewer.goto(`${base}/settings`);
    await expect(viewer.getByRole('button', { name: 'Appearance', exact: true })).toBeVisible();
    await expect(viewer.getByRole('button', { name: 'Users', exact: true })).toHaveCount(0);
    await page.screenshot({ path: join(temp, 'access-users-desktop.png'), fullPage: true });
    await row.getByRole('button', { name: 'Revoke access', exact: true }).click();
    await page.getByRole('button', { name: 'Revoke all sessions', exact: true }).click();
    await expect(page.getByRole('dialog')).toHaveCount(0);
    expect((await viewer.request.get(`${base}/api/auth/session`)).status()).toBe(401);
    await viewer.goto(`${base}/login`);
    await viewer.getByLabel('Email or existing username', { exact: true }).fill('access-viewer@example.com');
    await viewer.getByLabel('Password', { exact: true }).fill(password);
    await viewer.getByRole('button', { name: 'Sign in', exact: true }).click();
    await expect(viewer).toHaveURL(`${base}/loads`);
    await viewer.goto(`${base}/account`);
    await viewer.getByLabel('Current password', { exact: true }).fill(password);
    const replacement = randomBytes(20).toString('hex');
    await viewer.getByLabel('New password', { exact: true }).fill(replacement);
    await viewer.getByLabel('Confirm new password', { exact: true }).fill(replacement);
    await viewer.getByRole('button', { name: 'Change password', exact: true }).click();
    await expect(viewer).toHaveURL(`${base}/login`);
    await page.setViewportSize({ width: 390, height: 844 });
    await page.getByRole('button', { name: 'Collapse sidebar' }).click();
    await expect(page.locator('aside')).toHaveCSS('width', '64px');
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true);
    await page.screenshot({ path: join(temp, 'access-users-mobile.png'), fullPage: true });
    await page.setViewportSize({ width: 1440, height: 1000 });
    await page.getByRole('button', { name: 'Expand sidebar' }).click();
    expect(errors).toEqual([]);
  } finally { await context.close(); }
  console.log('Access E2E passed: roles, managed users, password login, 30-day session, permission denial, revocation, password change, responsive settings.');
}
