import { expect } from '@playwright/test';
import { join } from 'node:path';
import { profileFixture as f, seedProfileFixture } from './profile-fixture.mjs';

export async function runProfilesE2E({ page, base, sql, schema, temp }) {
  seedProfileFixture(sql, schema);
  await page.goto(`${base}/drivers/detail?id=${f.owner}`);
  await expect(page.getByRole('heading', { name: 'Morgan Hayes', exact: true })).toBeVisible();
  await expect(page.locator('[data-page-header] p')).toHaveCount(0);
  await expect(page.locator('aside').getByRole('button', { name: /Sign out/ })).toHaveCount(0);
  await expect(page.locator('main header').getByRole('link', { name: '101', exact: true })).toHaveAttribute('href', `/trucks/detail?id=${f.ownTruck}`);
  await expect(page.locator('main header').getByRole('link', { name: 'Dana Mitchell', exact: true })).toHaveAttribute('href', `/dispatchers/detail?id=${f.dispatcher}`);
  await expect(page.getByText('Ownership is separate from the operating driver.')).toHaveCount(0);
  const notes = page.getByRole('region', { name: 'Internal notes', exact: true });
  await notes.getByRole('button', { name: 'Add note', exact: true }).click();
  await notes.getByRole('textbox', { name: 'New internal note' }).fill('A dated driver note.');
  await notes.getByRole('button', { name: 'Save note', exact: true }).click();
  await expect(notes.getByText('A dated driver note.', { exact: true })).toBeVisible();
  await expect(notes.locator('time')).toHaveCount(1);
  await expect(notes).toContainText('investor-e2e');
  await page.getByRole('tab', { name: 'Assignments', exact: true }).click();
  await expect(page.getByLabel('Assignment type').locator('option')).toHaveCount(2);
  await expect(page.getByRole('columnheader', { name: 'Type', exact: true })).toHaveCount(0);
  await expect(page.getByRole('columnheader', { name: 'Truck', exact: true })).toBeVisible();
  await page.getByLabel('Assignment type').selectOption('dispatcher');
  await expect(page.getByRole('columnheader', { name: 'Dispatcher', exact: true })).toBeVisible();
  await page.getByRole('tab', { name: 'Ownership', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Investor statements', exact: true })).toBeVisible();
  const statement = page.getByRole('row').filter({ has: page.getByRole('cell', { name: '2026-09-28', exact: true }) }).filter({ hasText: '102' });
  await expect(statement).toContainText('10,000.00');
  await expect(statement).toContainText('8,800.00');
  await expect(statement).toContainText('8,300.00');
  const checkStatementAlignment = async () => {
    const table = page.getByRole('table', { name: 'Investor statement history' });
    for (const index of [2, 3, 4, 5]) {
      const header = table.locator('thead th').nth(index);
      const cell = table.locator('tbody tr').first().locator('td').nth(index);
      expect(await header.evaluate(el => getComputedStyle(el).textAlign)).toBe('right');
      const headerBox = await header.boundingBox();
      const cellBox = await cell.boundingBox();
      expect(Math.abs(headerBox.x + headerBox.width - cellBox.x - cellBox.width)).toBeLessThan(1);
    }
  };
  await checkStatementAlignment();
  await statement.getByRole('link', { name: 'Draft →', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Morgan Hayes 102', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Morgan Hayes', exact: true })).toHaveAttribute('href', `/investors/detail?id=${f.investor}`);
  await expect(page.getByRole('table', { name: 'Weekly investor pay', exact: true }).locator(':scope > tbody > tr > th')).toHaveCount(1);
  await expect(page.getByRole('table', { name: 'Weekly investor pay', exact: true }).locator(':scope > thead th')).toHaveText(['Investor', 'Truck', 'Driver', 'Dispatcher', 'Tariff', 'Loads', 'Total payable']);
  await expect(page.getByRole('link', { name: 'Jamie Carter', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Morgan Hayes 102', exact: true }).click({ button: 'right' });
  await expect(page.getByRole('menuitem', { name: 'Finalize truck', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  const summaryButton = page.getByRole('button', { name: 'Morgan Hayes 102', exact: true });
  await expect(page.getByRole('button', { name: 'Finalize truck', exact: true })).toHaveCount(0);
  const summaryColor = await summaryButton.locator('xpath=ancestor::tr[1]').evaluate(el => getComputedStyle(el).backgroundColor);
  expect(await page.locator(`#driver-${f.extraTruck}`).locator('xpath=..').evaluate(el => getComputedStyle(el).backgroundColor)).toBe(summaryColor);
  for (const cell of await page.locator(`#driver-${f.extraTruck} thead th`).all()) await expect(cell).toHaveCSS('background-color', summaryColor);
  await summaryButton.focus();
  await page.keyboard.press('Shift+F10');
  await expect(page.getByRole('menuitem', { name: 'Finalize truck' })).toBeFocused();
  await page.keyboard.press('Escape');
  await expect(summaryButton).toBeFocused();
  await expect(page.getByRole('link', { name: 'REVIEW-102', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'REVIEW-101', exact: true })).toHaveCount(0);
  await page.getByRole('button', { name: 'Morgan Hayes 102', exact: true }).click({ button: 'right' });
  await page.getByRole('menuitem', { name: 'Finalize truck', exact: true }).click();
  await page.getByRole('button', { name: 'Finalize settlement', exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Morgan Hayes 102', exact: true }).click({ button: 'right' });
  await expect(page.getByRole('menuitem', { name: 'Reopen truck', exact: true })).toBeVisible();
  await page.keyboard.press('Escape');
  sql(`SET search_path TO ${schema},public; UPDATE trucks SET active=false WHERE id='${f.extraTruck}'; UPDATE drivers SET active=false WHERE id='${f.owner}';`);
  const hiddenPay = await (await page.request.get(`${base}/api/investor-pay?weekStart=2026-09-28`)).json();
  expect(hiddenPay.drivers.some(d => d.id === f.extraTruck)).toBe(false);
  const historicalPay = await (await page.request.get(`${base}/api/investor-pay?weekStart=2026-09-28&truckId=${f.extraTruck}`)).json();
  expect(historicalPay.drivers.find(d => d.id === f.extraTruck).settlement.finalized).toBe(true);
  expect(historicalPay.revision).toBe(hiddenPay.revision);
  await page.getByRole('combobox', { name: 'Search records' }).fill('Morgan Hayes');
  const search = page.getByRole('region', { name: 'Global search' });
  await expect(search.getByRole('link', { name: /Terminated driver/ })).toHaveAttribute('href', `/drivers/detail?id=${f.owner}`);
  await expect(search.getByRole('link', { name: /Active investor/ })).toHaveAttribute('href', `/investors/detail?id=${f.investor}`);
  await page.keyboard.press('Escape');
  await page.goto(`${base}/investors/detail?id=${f.investor}`);
  await expect(page.getByRole('link', { name: 'Finalized →', exact: true })).toBeVisible();
  await checkStatementAlignment();
  await page.screenshot({ path: join(temp, 'investor-profile.png'), fullPage: true });
  await page.getByRole('link', { name: 'Finalized →', exact: true }).click();
  await expect(page.getByRole('button', { name: 'Morgan Hayes 102', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'REVIEW-102', exact: true })).toBeVisible();
  sql(`SET search_path TO ${schema},public; UPDATE trucks SET active=true WHERE id='${f.extraTruck}'; UPDATE drivers SET active=true WHERE id='${f.owner}';`);

  await page.goto(`${base}/accounting/investor-pay?weekStart=2026-09-28`);
  await page.getByRole('button', { name: 'Show all trucks', exact: true }).click();
  const payTable = page.getByRole('table', { name: 'Weekly investor pay', exact: true });
  const setupRow = payTable.getByRole('row').filter({ has: page.getByRole('link', { name: 'River Fleet Partners', exact: true }) });
  await expect(setupRow.getByRole('cell').nth(3)).toHaveText('Setup required');
  await expect(setupRow.getByRole('cell').last()).toHaveText('—');
  await expect(setupRow.getByRole('link', { name: 'Setup required' })).toHaveAttribute('href', '/accounting/driver-charges?tab=trucks');
  await expect(page.getByRole('heading', { name: 'Current trucks needing settlement terms' })).toHaveCount(0);
  await page.getByPlaceholder('Investor, truck, or load…').fill('River Fleet');
  await expect(payTable.locator(':scope > tbody > tr')).toHaveCount(1);
  await expect(setupRow).toBeVisible();
  await page.getByPlaceholder('Investor, truck, or load…').fill('');
  await page.screenshot({ path: join(temp, 'investor-pay.png'), fullPage: true });
  await page.goto(`${base}/trucks/detail?id=${f.extraTruck}`);
  const truckNotes = page.getByRole('region', { name: 'Internal notes', exact: true });
  await truckNotes.getByRole('button', { name: 'Add note' }).click();
  await truckNotes.getByRole('textbox', { name: 'New internal note' }).fill('A dated truck note.');
  await truckNotes.getByRole('button', { name: 'Save note' }).click();
  await expect(truckNotes.getByText('A dated truck note.', { exact: true })).toBeVisible();
  const location = page.getByRole('region', { name: 'Latest truck location' });
  await expect(location.getByText('Unit 102', { exact: true })).toBeVisible();
  await expect(location.getByRole('link')).toHaveCount(0);
  await page.getByRole('tab', { name: 'Assignments', exact: true }).click();
  await expect(page.getByRole('link', { name: 'Morgan Hayes', exact: true }).last()).toBeVisible();
  await expect(page.getByRole('row').filter({ hasText: 'Jamie Carter' }).last()).toContainText('Current');
  await expect(page.getByLabel('Assignment type')).toHaveCount(0);
  await page.goto(`${base}/dispatchers/detail?id=${f.dispatcher}`);
  await expect(page.getByRole('heading', { name: 'Dana Mitchell', exact: true })).toBeVisible();
  await expect(page.getByRole('link', { name: 'Jamie Carter', exact: true })).toBeVisible();
  const headerHeight = await page.locator('thead tr').first().evaluate(el => el.getBoundingClientRect().height);
  expect(headerHeight).toBe(36);
  await page.goto(`${base}/drivers/detail?id=${f.owner}`);
  await page.getByRole('tab', { name: 'Overview', exact: true }).click();
  await expect(page.getByText('A dated driver note.', { exact: true })).toBeVisible();
  await page.screenshot({ path: join(temp, 'driver-profile.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.getByRole('button', { name: 'Collapse sidebar' }).click();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: join(temp, 'driver-profile-mobile.png'), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  console.log(`Profile checks passed: dated notes, summary links, assignment switching, truck history, separate draft/finalized statements, and responsive UI. Screenshots: ${temp}`);
}
